### ISSUE TITLE
no va 

### ISSUE THREAD

**Issue by ngomezcn** [Randyy27/UAB-G.E.I-2023-2024#6]

**Comment by ngomezcn** [comment]
![image](https://github.com/Randyy27/UAB-G.E.I-2023-2024/assets/33960177/02228943-3db0-40e2-bdab-b561e816982f)

**Comment by Randyy27** [comment]
![image](https://github.com/Randyy27/UAB-G.E.I-2023-2024/assets/145675382/e1390cf8-71f0-4932-9fba-668310960139)
